### ISSUE TITLE
Hook pour faire un !updatesite automatiquement

### ISSUE THREAD

**Issue by sebvallee** [haum/website-content#1]
Pourquoi ne pas créer un hook qui mettrais a jour le site automatiquement? En cumulant cette fonction avec celle de l'issue https://github.com/haum/combot/issues/2 ca pourrait etre totalement automatique, tout en limitant le risque d'avoir un site foiré...

**Comment by matael** [comment]
Je suis un peu contre : je préfère savoir que la mise à jour est lancée manuellement par quelqu'un qui sait ce qu'il fait plutôt que par le premier qui pousse...

**Comment by matael** [comment]
Après discussion, on ferme ce ticket. L'update automatique est globalement une idée dangereuse.
